FROM gradle:jdk21 as builder
WORKDIR /libs
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY core/build.gradle core/build.gradle
RUN chmod +x ./gradlew
RUN ./gradlew dependencies --no-daemon || true
COPY src src
COPY core/src core/src
RUN ./gradlew build --no-daemon -x test
FROM openjdk:21-ea-21-slim
WORKDIR /app
COPY --from=builder /libs/build/libs/*.jar app.jar
ENTRYPOINT [ "java", "-Dspring.profiles.active=prod", "-jar", "app.jar" ]
